### ISSUE TITLE
[USER STORY]: As an IT person, I want to be able to create accounts for all the different types of users, so that each department has the correct type of access to the ERP system.

### ISSUE THREAD

**Issue by CeliaCaii** [mlee97/SOEN-390-Team5#30]
# State the Related Minimal Requirement:
    [8] The system should allow only registered users to access the information, possible with different accesses for different roles.

**Comment by pirasunt** [comment]
### As of the latest code merge (PR #28):
- A user of type `IT Department` can access a user management page where they can see all of the registered users
![image](https://user-images.githubusercontent.com/31664874/106835345-32815980-6665-11eb-8981-06d72318e91b.png)
---
- By clicking the EDIT button, the IT user can change the user's name, email and user type (access level)
![image](https://user-images.githubusercontent.com/31664874/106835434-56449f80-6665-11eb-9731-5764daca4e37.png)
---
- The `Create User` button also redirects the IT User to a new page, where they can create new users
![image](https://user-images.githubusercontent.com/31664874/106835496-6fe5e700-6665-11eb-9279-c5cc9d567192.png)
---
**_For now, the types of users are limited and are subject to change in future sprints_** 
---
- As such, this issue is resolved
